### ISSUE TITLE
Is it actually dead?

### ISSUE THREAD

**Issue by ZenSirzechs** [duncte123/CleverBot4J#2]
I have a python Discord bot that uses cleverbot.io and it's still working fine. Maybe they changed something else? 
I am not sure but I was really looking forward to using this API.

**Comment by duncte123** [comment]
You can try to use it but I've received a lot of timeouts with it

**Comment by ZenSirzechs** [comment]
I've tried and same thing happened to me. I tried using out libraries to post requests too but I am not experienced in Java so probs did something wrong.

Though If I do this in Python `requests.post('https://cleverbot.io/1.0/create', json={'user':user, 'key':key, 'nick':'Test'})`
it just still works. Maybe they changed something in their API?

**Comment by duncte123** [comment]
https://github.com/duncte123/CleverBot4J/blob/master/src/main/java/ml/duncte123/CleverBot4J/CleverbotBuilder.java#L97-L121

**Comment by ZenSirzechs** [comment]
I tried that but never worked. But thanks for your time.
